apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: maintemplate.default.svc.cluster.local
spec:
  request: b64_here
  usages:
    - digital signature
    - key encipherment
    - server auth
