apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grpc-maintemplate
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
{{- if .Values.domainSetup }}
    cert-manager.io/issuer: letsencrypt-prod
{{- end }}
spec:
{{- if .Values.domainSetup }}
  tls:
    - hosts:
      - grpc.maintemplate.{{ .Release.Name }}.getcouragenow.org
      secretName: maintemplate-grpc-{{ .Release.Name }}-tls
{{- end }}
  rules:  
  - http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-maintemplate
          servicePort: http2
{{- if .Values.domainSetup }}
    host: grpc.maintemplate.{{ .Release.Name }}.getcouragenow.org
{{- end }}